base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("users/", include("users.urls", namespace="users")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("payment/", include("payment.urls", namespace="payment")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_remove

app_name = "cart"

urlpatterns = [
    path("", cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", cart_add, name="cart_add"),
    path("remove/<int:product_id>/", cart_remove, name="cart_remove")
]

orders/urls.py
from django.urls import path
from .views import order_create

app_name = "orders"

urlpatterns = [
  path("create/", order_create, name="order_create")
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )
    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from main.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd["quantity"],
            override_quantity=cd["override"]
        )
    return redirect("cart:cart_detail")


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")


def cart_detail(request):
    cart = Cart(request)
    return render(request, "cart/cart_detail.html", {"cart": cart})

cart/templates/cart/cart_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %} Cart {% endblock %}

{% block header %}
  <div class="container mx-auto px-4 py-2">
    <h1 class="text-3xl my-4">Shopping Cart</h1>
  </div>
{% endblock header %}

{% block content %}
  <main class="container mx-auto px-4 py-2">
    <div class="bg-emerald-800 rounded-md mb-4"> 
      {% for item in cart %}
        {% with product=item.product %}
          <div class="p-4">
            <div class="flex gap-4 mb-2">
              <div class="min-w-[64px] h-[64px]">
                {% if product.image %}
                  <img class="w-[64px] h-[64px] object-cover" src="{{product.image.url}}" alt="{{product.name}}">
                {% else %}
                  <img class="w-[64px] h-[64px] object-cover" src="https://thumb.ac-illust.com/b1/b170870007dfa419295d949814474ab2_t.jpeg" alt="{{product.name}}">
                {% endif %}
              </div>
              <h4 class="text-white mb-2">
                <a 
                  href="{{product.get_absolute_url}}"
                  class="underline"
                >
                  {{product.name}}
                </a>
              </h4>
            </div>
            <p class="text-white mb-2">Quantity: {{item.quantity}}</p>
            <div>
              {% if product.discount %}
                <p class="line-through text-gray-400">$ {{product.price}}</p>
                <p class="text-white mb-2">$ {{product.discount_price}}</p>
              {% else %}
                <p class="text-white mb-2">$ {{product.price}}</p>
              {% endif %}
            </div>
            <div>
              <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                {% csrf_token %}
                <input 
                  type="submit" 
                  value="Remove"
                  class="block w-fit px-4 py-2 rounded-md mt-4 text-white bg-emerald-600 cursor-pointer"
                >
              </form>
            </div>
          </div>
        {% endwith %}
      {% endfor %}
    </div>

    <div>
      <h5 class="text-2xl">Total Price $ {{cart.get_total_price}}</h5>
    </div>
    <div class="flex gap-4">
      <a href="/shop" class="block w-fit px-4 py-2 rounded-md mt-4 text-white bg-emerald-800">Continue Shopping</a>
      
      {% with cart_quantity=cart|length  %}
        {% if cart_quantity > 0 %}
          <a href="{% url 'orders:order_create' %}" class="block w-fit px-4 py-2 rounded-md mt-4 text-white bg-emerald-800">Checkout</a>
        {% endif %}
      {% endwith %}
    </div>
  </main>
{% endblock content %}