base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("users/", include("users.urls", namespace="users")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("payment/", include("payment.urls", namespace="payment")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import login, registration, profile, logout

app_name = "users"

urlpatterns = [
    path("login/", login, name="login"),
    path("registration/", registration, name="registration"),
    path("profile/", profile, name="profile"),
    path("logout/", logout, name="logout"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    avatar = models.ImageField(
        upload_to="avatars/",
        blank=True,
        null=True,
    )
    country = models.CharField(blank=True, null=True, default=None)
    city = models.CharField(blank=True, null=True, default=None)
    address = models.CharField(blank=True, null=True, default=None)
    postal_code = models.CharField(blank=True, null=True, default=None)

    class Meta:
        db_table = "user"

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm, UserChangeForm
)
from .models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = User
        fields = ["username", "password"]
        

class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()
    country = forms.CharField()
    city = forms.CharField()
    address = forms.CharField()
    postal_code = forms.CharField()

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
            "country",
            "city",
            "address",
            "postal_code",
        )


class ProfileForm(UserChangeForm):
    avatar = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.EmailField()
    country = forms.CharField()
    city = forms.CharField()
    address = forms.CharField()
    postal_code = forms.CharField()

    class Meta:
        model = User
        fields = (
            "avatar",
            "first_name",
            "last_name",
            "username",
            "email",
            "country",
            "city",
            "address",
            "postal_code",
        )

users/views.py
from django.shortcuts import render, redirect
from django.contrib import auth, messages
from django.urls import reverse
from django.http import HttpResponseRedirect
from .forms import UserLoginForm, UserRegistrationForm, ProfileForm
from django.contrib.auth.decorators import login_required
from django.db.models import Prefetch
from orders.models import Order, OrderItem


def login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            user = auth.authenticate(username=username, password=password)

            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse("users:profile"))
    else:
        form = UserLoginForm()
    return render(request, "users/login.html", {"form": form})


def registration(request):
    if request.method == "POST":
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            messages.success(
                request, f"{user.username} successful registration !"
            )
            return HttpResponseRedirect(reverse("users:profile"))
    else:
        form = UserRegistrationForm()
        messages.MessageFailure(
            request, "Failed registration !"
        )
    return render(request, "users/registration.html")


@login_required
def profile(request):
    if request.method == "POST":
        form = ProfileForm(
            data=request.POST,
            instance=request.user,
            files=request.FILES
        )
        if form.is_valid():
            form.save()
            messages.success(request, "Profile was changed")
            return HttpResponseRedirect(reverse("users:profile"))
    else:
        form = ProfileForm(instance=request.user)

    orders = Order.objects.filter(user=request.user).prefetch_related(
        Prefetch(
            "items",
            queryset=OrderItem.objects.select_related("product"),
        )
    ).order_by("id")

    return render(
        request,
        "users/profile.html",
        {
            "form": form,
            "orders": orders
        }
    )


def logout(request):
    auth.logout(request)
    return redirect(reverse("main:index"))

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block title %} Login {% endblock %}

{% block header %}
  <div class="container mx-auto px-4 py-2">
    <h1 class="text-3xl my-4">Login</h1>
  </div>
{% endblock header %}

{% block content %}
  <main>
    <div class="container mx-auto px-4 py-2">
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eius repellat sed alias ab ex nesciunt sit deleniti cum sequi quos ipsa, soluta reiciendis!</p>
      <form class="pb-4" action="{% url 'users:login' %}" method="POST">
        {% csrf_token %}
        {% if request.GET.next %}
          <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        
        <div class="mb-4 mt-4">
          <input 
            class="px-4 py-2 border rounded-md"
            type="text" 
            name="username" 
            placeholder="username"
            value="{% if form.username.value %} {{form.username.value}} {% endif %}"
            required
          >
        </div>
        <div>
          <input 
            class="px-4 py-2 border rounded-md"
            type="password" 
            name="password" 
            placeholder="password"
            autocomplete="off"
            required
          >
        </div>
        <div>
          <input 
            class="block w-fit px-4 py-2 rounded-md mt-4 text-white bg-emerald-800 cursor-pointer"
            type="submit" 
            value="Login"
          >
        </div>
      </form>
      <hr>
      <div class="mt-4">
        <a class="block mb-2 text-blue-600 font-medium" href="{% url 'users:registration' %}">Create Account</a>
        <a class="block text-blue-600 font-medium" href="#">Reset Password</a>
      </div>
    </div>
  </main>
{% endblock content %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block title %} User Profile {% endblock %}

{% block header %}
  <div class="container mx-auto px-4 py-2">
    <h1 class="text-3xl my-4">Profile</h1>
  </div>
{% endblock header %}

{% block content %}
  <main>
    <div class="container mx-auto px-4 py-2">
      <form 
        action="{% url 'users:profile' %}"
        method="POST"
        enctype="multipart/form-data"
      >
        {% csrf_token %}

        <div class="flex gap-8 items-center justify-between">
          <div class="flex-1">
            {% if user.avatar %}
              <img src="{{user.avatar.url}}" alt="Avatar">
            {% else %}
              <img src="{% static 'img/no_img.webp' %}" alt="No Avatar">
            {% endif %}
            <input type="file" name="avatar" accept="image/*" class="mt-4">
          </div>
          <div class="flex-1">
            <label class="flex mb-4 gap-2 justify-between items-center">
              <span>First Name:</span>
              <input 
                type="text"
                name="first_name"
                placeholder="Type here..."
                value="{{form.first_name.value}}"
                required
                class="px-4 py-2 border rounded-md"
              >
            </label>
            <label class="flex mb-4 gap-2 justify-between items-center">
              <span>Last Name:</span>
              <input 
                type="text"
                name="last_name"
                placeholder="Type here..."
                value="{{form.last_name.value}}"
                required
                class="px-4 py-2 border rounded-md"
              >
            </label>
            <label class="flex mb-4 gap-2 justify-between items-center">
              <span>Email:</span>
              <input 
                type="text"
                name="email"
                placeholder="Type here..."
                value="{{form.email.value}}"
                required
                class="px-4 py-2 border rounded-md"
              >
            </label>
            <label class="flex mb-4 gap-2 justify-between items-center">
              <span>Username:</span>
              <input 
                type="text"
                name="username"
                placeholder="Type here..."
                value="{{form.username.value}}"
                required
                class="px-4 py-2 border rounded-md"
              >
            </label>
            <label class="flex mb-4 gap-2 justify-between items-center">
              <span>Country:</span>
              <input 
                type="text"
                name="country"
                placeholder="Type here..."
                value="{{form.country.value}}"
                required
                class="px-4 py-2 border rounded-md"
              >
            </label>
            <label class="flex mb-4 gap-2 justify-between items-center">
              <span>City:</span>
              <input 
                type="text"
                name="city"
                placeholder="Type here..."
                value="{{form.city.value}}"
                required
                class="px-4 py-2 border rounded-md"
              >
            </label>
            <label class="flex mb-4 gap-2 justify-between items-center">
              <span>Address:</span>
              <input 
                type="text"
                name="address"
                placeholder="Type here..."
                value="{{form.address.value}}"
                required
                class="px-4 py-2 border rounded-md"
              >
            </label>
            <label class="flex mb-4 gap-2 justify-between items-center">
              <span>Postal Code:</span>
              <input 
                type="text"
                name="postal_code"
                placeholder="Type here..."
                value="{{form.postal_code.value}}"
                required
                class="px-4 py-2 border rounded-md"
              >
            </label>
            <button class="block w-fit px-4 py-2 rounded-md mt-4 text-white bg-emerald-800 cursor-pointer" type="submit">Save</button>
          </div>
        </div>
      </form>
    </div>
    <div class="container mx-auto px-4 py-2">
      <h2 class="text-3xl mt-4">Your Orders</h2>
      {% if orders  %}
        <div>
          {% for order in orders %}
            <div class="mb-8">
              <h5 class="mb-4 mt-4 text-2xl">Order ID #{{order.id}}</h5>
              {% for item in order.items.all %}
                <div class="flex gap-4 items-center">
                  <img 
                    src="{{item.product.image.url}}" 
                    alt="{{item.product.name}}"
                    class="w-16 h-16 object-cover"
                  >
                  <div>
                    <h4>
                      <a href="{{item.product.get_absolute_url}}">
                        {{item.product.name}}
                      </a>
                    </h4>
                    <p>
                      Quantity: {{item.quantity}}
                    </p>
                    <p>Price: {{item.price}}</p>
                    <p>Order Created in: {{order.created|date:"Y/m/d h:m:s"}}</p>
                  </div>
                </div>
              {% endfor %}
            </div>
          {% endfor %}
        </div>
      {% else %}
        <h4>You haven't ordered anything yet.</h4>
      {% endif %}
    </div>
  </main>
{% endblock content %}

users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}

{% block title %} Registration {% endblock %}

{% block header %}
  <div class="container mx-auto px-4 py-2">
    <h1 class="text-3xl my-4">Registration</h1>
  </div>
{% endblock header %}

{% block content %}
  <main>
    <div class="container mx-auto px-4 py-2">
      <form class="max-w-[580px]" action="{% url 'users:registration' %}" method="POST">
        {% csrf_token %}
        <label class="flex mb-4 gap-2 justify-between items-center">
          <span>First Name:</span>
          <input 
            type="text"
            name="first_name"
            placeholder="Type here..."
            required
            class="px-4 py-2 border rounded-md"
          >
        </label>
        <label class="flex mb-4 gap-2 justify-between items-center">
          <span>Last Name:</span>
          <input 
            type="text"
            name="last_name"
            placeholder="Type here..."
            required
            class="px-4 py-2 border rounded-md"
          >
        </label>
        <label class="flex mb-4 gap-2 justify-between items-center">
          <span>Username:</span>
          <input 
            type="text"
            name="username"
            placeholder="Type here..."
            required
            class="px-4 py-2 border rounded-md"
          >
        </label>
        <label class="flex mb-4 gap-2 justify-between items-center">
          <span>Email:</span>
          <input 
            type="text"
            name="email"
            placeholder="Type here..."
            required
            class="px-4 py-2 border rounded-md"
          >
        </label>
        <label class="flex mb-4 gap-2 justify-between items-center">
          <span>Password:</span>
          <input 
            type="password"
            name="password1"
            placeholder="Type here..."
            required
            class="px-4 py-2 border rounded-md"
          >
        </label>
        <label class="flex mb-4 gap-2 justify-between items-center">
          <span>Confirm Password:</span>
          <input 
            type="password"
            name="password2"
            placeholder="Type here..."
            required
            class="px-4 py-2 border rounded-md"
          >
        </label>
        <label class="flex mb-4 gap-2 justify-between items-center">
          <span>Country:</span>
          <input 
            type="text"
            name="country"
            placeholder="Type here..."
            required
            class="px-4 py-2 border rounded-md"
          >
        </label>
        <label class="flex mb-4 gap-2 justify-between items-center">
          <span>City:</span>
          <input 
            type="text"
            name="city"
            placeholder="Type here..."
            required
            class="px-4 py-2 border rounded-md"
          >
        </label>
        <label class="flex mb-4 gap-2 justify-between items-center">
          <span>Address:</span>
          <input 
            type="text"
            name="address"
            placeholder="Type here..."
            required
            class="px-4 py-2 border rounded-md"
          >
        </label>
        <label class="flex mb-4 gap-2 justify-between items-center">
          <span>Postal Code:</span>
          <input 
            type="text"
            name="postal_code"
            placeholder="Type here..."
            required
            class="px-4 py-2 border rounded-md"
          >
        </label>
        <button
          class="block w-fit px-4 py-2 rounded-md mt-4 text-white bg-emerald-800 cursor-pointer" 
          type="submit"
        > 
          Create Account
        </button>
      </form>
    </div>
  </main>
{% endblock content %}