base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("users/", include("users.urls", namespace="users")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("payment/", include("payment.urls", namespace="payment")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_remove

app_name = "cart"

urlpatterns = [
    path("", cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", cart_add, name="cart_add"),
    path("remove/<int:product_id>/", cart_remove, name="cart_remove")
]

main/urls.py
from django.urls import path
from .views import (
    index, product_details, 
    shop, category,
    about, contacts
)

app_name = "main"

urlpatterns = [
    path("", index, name="index"),
    path("shop/", shop, name="shop"),
    path("shop/<slug:category_slug>", category, name="category"),
    path("shop/<slug:category_slug>/<slug:product_slug>", product_details, name="product_details"),
    path("about/", about, name="about"),
    path("contacts/", contacts, name="contacts"),
]

users/urls.py
from django.urls import path
from .views import login, registration, profile, logout

app_name = "users"

urlpatterns = [
    path("login/", login, name="login"),
    path("registration/", registration, name="registration"),
    path("profile/", profile, name="profile"),
    path("logout/", logout, name="logout"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %} {% endblock %}</title>

  {% block slider_css %}
  {% endblock %}
  {% block fancy_css %}
  {% endblock fancy_css %}
  {% block fancy_js %}
  {% endblock fancy_js %}

  <script src="https://cdn.tailwindcss.com"></script>
</head>

<body>
  <nav class="bg-emerald-800 sticky top-0 z-[2]">
    <div class="container min-h-[90px] mx-auto px-4 py-2 flex justify-between items-center">
      <div>
        <h4>
          <a href="/" class="text-white text-2xl">StoreEVN</a>
        </h4>
      </div>
      <div class="flex items-center gap-8">
        <!-- Cart start -->
        <div>
          <a href="{% url 'cart:cart_detail' %}" class="relative">
            <span class="flex justify-center items-center absolute right-[-12px] top-[-12px] bg-red-600 leading-0 text-white text-[10px] w-5 h-5 rounded-full">
              {% with cart_quantity=cart|length %}
                {% if cart_quantity > 0 %}
                  {{cart_quantity}}
                {% else %}
                  0
                {% endif %}
              {% endwith %}
            </span>
            <svg viewBox="0 0 24 24" width="24" height="24">
              <path class="fill-white" d="M24,3H4.242L4.2,2.649A3,3,0,0,0,1.222,0H0V2H1.222a1,1,0,0,1,.993.883L3.8,16.351A3,3,0,0,0,6.778,19H20V17H6.778a1,1,0,0,1-.993-.884L5.654,15H21.836Z"/>
              <circle class="fill-white" cx="7" cy="22" r="2"/>
              <circle class="fill-white" cx="17" cy="22" r="2"/>
            </svg>
          </a>
        </div>
        <!-- Cart End -->
        <button data-mobileMenuBtn class="min-[768px]:hidden">
          <svg viewBox="0 0 490.667 490.667" width="24" height="24">
            <g class="fill-white">
              <path
                d="M469.333,224h-448C9.551,224,0,233.551,0,245.333c0,11.782,9.551,21.333,21.333,21.333h448   c11.782,0,21.333-9.551,21.333-21.333C490.667,233.551,481.115,224,469.333,224z" />
              <path
                d="M21.333,117.333h448c11.782,0,21.333-9.551,21.333-21.333s-9.551-21.333-21.333-21.333h-448C9.551,74.667,0,84.218,0,96   S9.551,117.333,21.333,117.333z" />
              <path
                d="M469.333,373.333h-448C9.551,373.333,0,382.885,0,394.667C0,406.449,9.551,416,21.333,416h448   c11.782,0,21.333-9.551,21.333-21.333C490.667,382.885,481.115,373.333,469.333,373.333z" />
            </g>
          </svg>
        </button>
        <div 
          data-menuContainer
          class="
            flex items-center jusfity-between gap-8
            max-[768px]:flex-col
            max-[768px]:fixed 
            max-[768px]:left-[-5000px]
            max-[768px]:top-[90px] 
            max-[768px]:p-8 
            max-[768px]:w-full 
            max-[768px]:h-full
            max-[768px]:bg-emerald-800
          "
        >
          <ul class="flex gap-4 z-40 max-[768px]:flex-col max-[768px]:text-center">
            <li>
              <a 
                href="{% url 'main:index' %}" 
                class="
                  hover:text-emerald-200 transition-color duration-300 text-xl
                  {% if request.get_full_path == '/' %} text-red-600 {% else %} text-white {% endif %}
                "
              >
                Home
              </a>
            </li>
            <li>
              <a 
                href="{% url 'main:shop' %}" 
                class="
                  hover:text-emerald-200 transition-color duration-300 text-xl
                  {% if request.get_full_path == '/shop/' %} text-red-600 {% else %} text-white {% endif %}
                "
              >
                Shop
              </a>
            </li>
            <li>
              <a 
                href="{% url 'main:about' %}" 
                class="
                  hover:text-emerald-200 transition-color duration-300 text-xl
                  {% if request.get_full_path == '/about/' %} text-red-600 {% else %} text-white {% endif %}
                "
              >
                About
              </a>
            </li>
            <li>
              <a 
                href="{% url 'main:contacts' %}" 
                class="
                  hover:text-emerald-200 transition-color duration-300 text-xl
                  {% if request.get_full_path == '/contacts/' %} text-red-600 {% else %} text-white {% endif %}
                "
              >
                Contacts
              </a>
            </li>
          </ul>
          <div class="flex gap-4">
            {% if request.user.is_authenticated %}
              <a 
                href="{% url 'users:profile' %}"
                class="
                  bg-emerald-600 
                  rounded-md px-4 
                  py-2 text-emerald-200
                  transition-color
                  duration-300
                  hover:bg-emerald-300
                  hover:text-emerald-800
                "
              >
                Profile
              </a>
              <a href="{% url 'users:logout' %}" 
                class="
                  bg-emerald-600 
                  rounded-md px-4 
                  py-2 text-emerald-200
                  transition-color
                  duration-300
                  hover:bg-emerald-300
                  hover:text-emerald-800
                "
              >
                Sign Out
              </a>
            {% else %}
              <a href="{% url 'users:login' %}" 
                class="
                  bg-emerald-600 
                  rounded-md px-4 
                  py-2 text-emerald-200
                  transition-color
                  duration-300
                  hover:bg-emerald-300
                  hover:text-emerald-800
                "
              >
                Sign In
              </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </nav>

  <header>
    {% block header %}
    {% endblock header %}
  </header>

  {% block content %}
  {% endblock content %}

  <footer></footer>

  <script src="{% static 'js/script.js' %}"></script>
  {% block slider_js %}
  {% endblock slider_js %}
</body>

</html>